// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXq5Oz_ER5Wuk-JqnQNuGDf4Ki5eKKpe4',
    appId: '1:668124880321:web:00e0a50543ae907540e340',
    messagingSenderId: '668124880321',
    projectId: 'botps-1da99',
    authDomain: 'botps-1da99.firebaseapp.com',
    storageBucket: 'botps-1da99.firebasestorage.app',
    measurementId: 'G-DFW2DF3SQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2y9j0YsSm9e8casc1fiUXjBbx1Ns8zyI',
    appId: '1:668124880321:android:588f1f60765a2d4f40e340',
    messagingSenderId: '668124880321',
    projectId: 'botps-1da99',
    storageBucket: 'botps-1da99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPiC0N_izpIcCGWzXT7Q6MBYVsc32MqIY',
    appId: '1:668124880321:ios:008421b46f5c79e840e340',
    messagingSenderId: '668124880321',
    projectId: 'botps-1da99',
    storageBucket: 'botps-1da99.firebasestorage.app',
    androidClientId: '668124880321-mnvn1m30qo9egcktbbfv2tdjh2hkisui.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPiC0N_izpIcCGWzXT7Q6MBYVsc32MqIY',
    appId: '1:668124880321:ios:008421b46f5c79e840e340',
    messagingSenderId: '668124880321',
    projectId: 'botps-1da99',
    storageBucket: 'botps-1da99.firebasestorage.app',
    androidClientId: '668124880321-mnvn1m30qo9egcktbbfv2tdjh2hkisui.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXq5Oz_ER5Wuk-JqnQNuGDf4Ki5eKKpe4',
    appId: '1:668124880321:web:d8eddb0565c8a48440e340',
    messagingSenderId: '668124880321',
    projectId: 'botps-1da99',
    authDomain: 'botps-1da99.firebaseapp.com',
    storageBucket: 'botps-1da99.firebasestorage.app',
    measurementId: 'G-5D48GE7C3C',
  );
}
